// Auto-generated from data/findingsFilter.js by scripts/generate-filter-map.js. Do not hand-edit; regenerate instead.
var FILTER_MAP = {
  filtersByDataType: {
    'Container Image Findings': [
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Package Name', data_field: 'vulnerability__misc__pkg_name', column_name: 'Package Name' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Ins Version', data_field: 'vulnerability__misc__ins_version', column_name: 'Ins Version' },
      { filter: 'Fix Version', data_field: 'vulnerability__misc__fix_version', column_name: 'Fix Version' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'NVD URL', data_field: 'vulnerability__misc__nvd_url', column_name: 'NVD URL' },
      { filter: 'CVE', data_field: 'vulnerability__misc__cve_id', column_name: 'CVE' },
      { filter: 'CWE', data_field: 'vulnerability__misc__cwe', column_name: 'CWE' },
      { filter: 'NVD CVSS2 Vectors', data_field: 'vulnerability__misc__nvd_cvss2_vectors', column_name: 'NVD CVSS2 Vectors' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'CVSS Score', data_field: 'vulnerability__cvss_score', column_name: 'CVSS Score' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Publish Date', data_field: 'vulnerability__misc__publish_date', column_name: 'Publish Date' },
      { filter: 'Modification Date', data_field: 'vulnerability__misc__modification_date', column_name: 'Modification Date' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
    ],
    'Static Code Analysis Finding': [
      { filter: 'From Hotspot', data_field: 'misc__from_hotspot', column_name: 'From Hotspot' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Type', data_field: 'vulnerability__misc__type', column_name: 'Type' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Sonarqube Tags', data_field: 'vulnerability__misc__sonarqube_tags', column_name: 'Sonarqube Tags' },
      { filter: 'Security Category', data_field: 'vulnerability__misc__security_category', column_name: 'Security Category' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'File Name', data_field: 'misc__filename', column_name: 'File Name' },
      { filter: 'Branch', data_field: 'misc__branch', column_name: 'Branch' },
      { filter: 'Effort', data_field: 'vulnerability__misc__effort', column_name: 'Effort' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'Repository Name', data_field: 'misc__repo', column_name: 'Repository Name' },
      { filter: 'OWASP', data_field: 'vulnerability__misc__owasp', column_name: 'OWASP' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'CWE', data_field: 'vulnerability__misc__cwe', column_name: 'CWE' },
    ],
    'STIG Findings': [
      { filter: 'Tool Output', data_field: 'tool_output', column_name: 'Tool Output' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Cluster Name', data_field: 'misc__cluster', column_name: 'Cluster Name' },
      { filter: 'Fix ID', data_field: 'vulnerability__misc__fixid', column_name: 'Fix ID' },
      { filter: 'Rule ID', data_field: 'vulnerability__misc__ruleID', column_name: 'Rule ID' },
      { filter: 'Check ID', data_field: 'vulnerability__misc__checkid', column_name: 'Check ID' },
      { filter: 'Profile', data_field: 'vulnerability__misc__profile', column_name: 'Profile' },
      { filter: 'Version', data_field: 'vulnerability__misc__version', column_name: 'Version' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
    ],
    'CIS K8s Benchmark Findings': [
      { filter: 'Test Number', data_field: 'misc__test_number', column_name: 'Test Number' },
      { filter: 'Tool Output', data_field: 'tool_output', column_name: 'Tool Output' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Compliance Type', data_field: 'vulnerability__misc__compliance_type', column_name: 'Compliance Type' },
      { filter: 'Group Text', data_field: 'vulnerability__misc__group_text', column_name: 'Group Text' },
      { filter: 'Benchmark', data_field: 'vulnerability__misc__benchmark', column_name: 'Benchmark' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Expected Result', data_field: 'vulnerability__misc__expected_result', column_name: 'Expected Result' },
      { filter: 'Type', data_field: 'vulnerability__misc__type', column_name: 'Vulnerability Type' },
    ],
    'KIEM Findings': [
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Namespace', data_field: 'misc__namespace', column_name: 'Namespace' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Cluster Name', data_field: 'misc__cluster', column_name: 'Cluster Name' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
    ],
    'Host-Endpoint Findings': [
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Asset Host IP', data_field: 'asset__host_ip', column_name: 'Asset Host IP' },
      { filter: 'Asset Host Name', data_field: 'asset__host_name', column_name: 'Asset Host Name' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'CVSS Score', data_field: 'vulnerability__cvss_score', column_name: 'CVSS Score' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'CVE', data_field: 'vulnerability__misc__cve', column_name: 'CVE' },
      { filter: 'XREF', data_field: 'vulnerability__misc__xref', column_name: 'XREF' },
      { filter: 'Plugin Type', data_field: 'vulnerability__misc__plugin_type', column_name: 'Plugin Type' },
      { filter: 'Plugin Family', data_field: 'vulnerability__misc__pluginFamily', column_name: 'Plugin Family' },
      { filter: 'Script Version', data_field: 'vulnerability__misc__script_version', column_name: 'Script Version' },
    ],
    'Cluster Findings': [
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Tool Output', data_field: 'tool_output', column_name: 'Tool Output' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Namespace', data_field: 'misc__namespace', column_name: 'Namespace' },
      { filter: 'Cluster Name', data_field: 'misc__cluster', column_name: 'Cluster Name' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
    ],
    'IaC Findings': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'CVSS Score', data_field: 'vulnerability__cvss_score', column_name: 'CVSS Score' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Check ID', data_field: 'vulnerability__misc__check_id', column_name: 'Check ID' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Tool Output', data_field: 'tool_output', column_name: 'Tool Output' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Framework', data_field: 'misc__framework', column_name: 'Framework' },
      { filter: 'Branch', data_field: 'misc__branch', column_name: 'Branch' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Repository Name', data_field: 'misc__repo', column_name: 'Repository Name' },
      { filter: 'Resource', data_field: 'misc__resource', column_name: 'Resource' },
      { filter: 'File Path', data_field: 'misc__file_path', column_name: 'File Path' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
    ],
    'Secret Scan Findings': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Repository Name', data_field: 'misc__repo', column_name: 'Repository Name' },
      { filter: 'Email', data_field: 'misc__email', column_name: 'Email' },
      { filter: 'Verified', data_field: 'misc__verified', column_name: 'Verified' },
      { filter: 'Source Name', data_field: 'misc__source_name', column_name: 'Source Name' },
      { filter: 'Source Domain', data_field: 'misc__source_domain', column_name: 'Source Domain' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'File', data_field: 'misc__file', column_name: 'File' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Detector Name', data_field: 'vulnerability__misc__detector_name', column_name: 'Detector Name' },
      { filter: 'Decoder Name', data_field: 'vulnerability__misc__decoder_name', column_name: 'Decoder Name' },
    ],
    'DAST Findings 1': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'CWE', data_field: 'vulnerability__misc__cwe', column_name: 'CWE' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Params', data_field: 'misc__param', column_name: 'Params' },
      { filter: 'Method', data_field: 'misc__method', column_name: 'Method' },
      { filter: 'Evidence', data_field: 'misc__evidence', column_name: 'Evidence' },
      { filter: 'Other Info', data_field: 'vulnerability__misc__otherinfo', column_name: 'Other Info' },
    ],
    'DAST Findings 2': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Confidence', data_field: 'vulnerability__misc__confidence', column_name: 'Confidence' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Asset Type Alias', data_field: 'asset__type__alias', column_name: 'Asset Type Alias' },
      { filter: 'Serial Number', data_field: 'misc__serial_number', column_name: 'Serial Number' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Vulnerability Classifications', data_field: 'vulnerability__misc__vulnerability_classifications', column_name: 'Vulnerability Classifications' },
      { filter: 'Issue Detail', data_field: 'vulnerability__misc__issueDetail', column_name: 'Issue Detail' },
    ],
    'CX KICS': [
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
    ],
    'CX CONTAINERS': [
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'CVSS Score', data_field: 'vulnerability__cvss_score', column_name: 'CVSS Score' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
    ],
    'SAST Findings': [
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Path', data_field: 'misc__path', column_name: 'Path' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'OWASP', data_field: 'vulnerability__misc__owasp', column_name: 'OWASP' },
      { filter: 'CWE', data_field: 'vulnerability__misc__cwe', column_name: 'CWE' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Scan Workflow Run URL', data_field: 'misc__scan_workflow_run_url', column_name: 'Scan Workflow Run URL' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Category', data_field: 'vulnerability__misc__category', column_name: 'Category' },
      { filter: 'Technology', data_field: 'vulnerability__misc__technology', column_name: 'Technology' },
      { filter: 'Repository Name', data_field: 'misc__repo', column_name: 'Repository Name' },
      { filter: 'Sub Category', data_field: 'vulnerability__misc__sub_category', column_name: 'Sub Category' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Branch', data_field: 'misc__scan_workflow_scan_ref', column_name: 'Branch' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Workflow Run ID', data_field: 'misc__workflow_run_id', column_name: 'Workflow Run ID' },
      { filter: 'Scan Commit', data_field: 'misc__scan_commit', column_name: 'Scan Commit' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Source', data_field: 'misc__source', column_name: 'Source' },
    ],
    'CX SAST': [
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
    ],
    'CX SCA': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'CVSS Score', data_field: 'vulnerability__cvss_score', column_name: 'CVSS Score' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
    ],
    'Cloud Findings': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Finding Name', data_field: 'misc__message', column_name: 'Finding Name' },
      { filter: 'Cloud Account Type', data_field: 'misc__cloud_type', column_name: 'Cloud Account Type' },
      { filter: 'Cloud Account', data_field: 'misc__cloud_account', column_name: 'Cloud Account' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Compliance Name', data_field: 'vulnerability__misc__compliance', column_name: 'Compliance Name' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Tool Output', data_field: 'tool_output', column_name: 'Tool Output' },
      { filter: 'Asset Tags', data_field: 'asset__tags', column_name: 'Asset Tags' },
    ],
    '5G Security Findings': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Threat ID', data_field: 'misc__threat_id', column_name: 'Threat ID' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Tool Output', data_field: 'tool_output', column_name: 'Tool Output' },
      { filter: 'Cluster Name', data_field: 'misc__cluster', column_name: 'Cluster Name' },
      { filter: 'Namespace', data_field: 'misc__namespace', column_name: 'Namespace' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
    ],
    'Linux VM Vulnerability Findings': [
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Package Name', data_field: 'vulnerability__misc__pkg_name', column_name: 'Package Name' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Ins Version', data_field: 'vulnerability__misc__ins_version', column_name: 'Ins Version' },
      { filter: 'Fix Version', data_field: 'vulnerability__misc__fix_version', column_name: 'Fix Version' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'CVSS v3 Score', data_field: 'vulnerability__misc__cvss_v3_score', column_name: 'CVSS v3 Score' },
      { filter: 'NVD URL', data_field: 'vulnerability__misc__nvd_url', column_name: 'NVD URL' },
      { filter: 'CVE', data_field: 'vulnerability__misc__cve_id', column_name: 'CVE' },
      { filter: 'CWE', data_field: 'vulnerability__misc__cwe', column_name: 'CWE' },
      { filter: 'NVD CVSS2 Vectors', data_field: 'vulnerability__misc__nvd_cvss2_vectors', column_name: 'NVD CVSS2 Vectors' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'CVSS v2 Score', data_field: 'vulnerability__misc__cvss_v2_score', column_name: 'CVSS v2 Score' },
      { filter: 'CVSS Score', data_field: 'vulnerability__cvss_score', column_name: 'CVSS Score' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Publish Date', data_field: 'vulnerability__misc__publish_date', column_name: 'Publish Date' },
      { filter: 'NVD CVSS3 Vectors', data_field: 'vulnerability__misc__nvd_cvss3_vectors', column_name: 'NVD CVSS3 Vectors' },
      { filter: 'Modification Date', data_field: 'vulnerability__misc__modification_date', column_name: 'Modification Date' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Cloud Account Type', data_field: 'misc__cloud_account_type', column_name: 'Cloud Account Type' },
      { filter: 'Cloud Account', data_field: 'misc__cloud_account_id', column_name: 'Cloud Account' },
    ],
    'VM Malware Findings': [
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'VM' },
      { filter: 'Signature', data_field: 'misc__clamAVSignature', column_name: 'Signature' },
      { filter: 'OS', data_field: 'misc__os', column_name: 'OS' },
      { filter: 'Cloud Account Type', data_field: 'misc__cloud_account_type', column_name: 'Cloud Account Type' },
      { filter: 'Cloud Account', data_field: 'misc__cloud_account_id', column_name: 'Cloud Account' },
      { filter: 'MIME Type', data_field: 'misc__metadata__mimetype', column_name: 'MIME Type' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
    ],
    'API Security Findings': [
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Cluster Name', data_field: 'misc__clusterName', column_name: 'Cluster Name' },
      { filter: 'Service Name', data_field: 'misc__serviceName', column_name: 'Service Name' },
      { filter: 'Occurrences', data_field: 'misc__occurrences', column_name: 'Occurrences' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Request Method', data_field: 'misc__requestMethod', column_name: 'Request Method' },
      { filter: 'Request Path', data_field: 'misc__requestPath', column_name: 'Request Path' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Status Code', data_field: 'misc__status_code', column_name: 'Status Code' },
      { filter: 'Port', data_field: 'misc__port', column_name: 'Port' },
    ],
    'SARIF Findings': [
      { filter: 'Source Tool', data_field: 'misc__source_tool', column_name: 'Source Tool' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Location', data_field: 'misc__display_location', column_name: 'Location' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Asset Category', data_field: 'asset__type__category', column_name: 'Asset Category' },
      { filter: 'Asset Type', data_field: 'asset__type__name', column_name: 'Asset Type' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
    ],
    'Windows VM Vulnerability Findings': [
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'CVSS Score', data_field: 'vulnerability__cvss_score', column_name: 'CVSS Score' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'OS', data_field: 'misc__os', column_name: 'OS' },
      { filter: 'Cloud Account Type', data_field: 'misc__cloud_account_type', column_name: 'Cloud Account Type' },
      { filter: 'Cloud Account', data_field: 'misc__cloud_account_id', column_name: 'Cloud Account' },
      { filter: 'Package Name', data_field: 'vulnerability__misc__pkg_name', column_name: 'Package Name' },
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Ins Version', data_field: 'vulnerability__misc__ins_version', column_name: 'Ins Version' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'CWE', data_field: 'vulnerability__misc__cwe', column_name: 'CWE' },
      { filter: 'CVE', data_field: 'vulnerability__misc__cve', column_name: 'CVE' },
    ],
    'DAST Findings': [
      { filter: 'Location', data_field: 'location', column_name: 'Location' },
      { filter: 'Status', data_field: 'status', column_name: 'Status' },
      { filter: 'Asset Type', data_field: 'asset__type', column_name: 'Asset Type' },
      { filter: 'Data Type', data_field: 'vulnerability__data_type', column_name: 'Data Type' },
      { filter: 'Vulnerability Name', data_field: 'vulnerability__name', column_name: 'Vulnerability Name' },
      { filter: 'Origin Risk Factor', data_field: 'vulnerability__origin_risk_factor', column_name: 'Origin Risk Factor' },
      { filter: 'Solution', data_field: 'vulnerability__solution', column_name: 'Solution' },
      { filter: 'Identification Numbers', data_field: 'vulnerability__identification_numbers', column_name: 'Identification Numbers' },
      { filter: 'Asset Name', data_field: 'asset__name', column_name: 'Asset Name' },
      { filter: 'Label', data_field: 'asset__label', column_name: 'Label' },
      { filter: 'OWASP', data_field: 'vulnerability__misc__owasp', column_name: 'OWASP' },
    ],
  },
  genericFilterMap: {
    vulnerability__identification_numbers: { filter: 'Identification Numbers', column_name: 'Identification Numbers' },
    asset__name: { filter: 'Asset Name', column_name: 'Asset Name' },
    vulnerability__misc__pkg_name: { filter: 'Package Name', column_name: 'Package Name' },
    location: { filter: 'Location', column_name: 'Location' },
    vulnerability__misc__ins_version: { filter: 'Ins Version', column_name: 'Ins Version' },
    vulnerability__misc__fix_version: { filter: 'Fix Version', column_name: 'Fix Version' },
    status: { filter: 'Status', column_name: 'Status' },
    asset__label: { filter: 'Label', column_name: 'Label' },
    vulnerability__misc__nvd_url: { filter: 'NVD URL', column_name: 'NVD URL' },
    vulnerability__misc__cve_id: { filter: 'CVE', column_name: 'CVE' },
    vulnerability__misc__cwe: { filter: 'CWE', column_name: 'CWE' },
    vulnerability__misc__nvd_cvss2_vectors: { filter: 'NVD CVSS2 Vectors', column_name: 'NVD CVSS2 Vectors' },
    vulnerability__data_type: { filter: 'Data Type', column_name: 'Data Type' },
    vulnerability__cvss_score: { filter: 'CVSS Score', column_name: 'CVSS Score' },
    vulnerability__origin_risk_factor: { filter: 'Origin Risk Factor', column_name: 'Origin Risk Factor' },
    vulnerability__misc__publish_date: { filter: 'Publish Date', column_name: 'Publish Date' },
    vulnerability__misc__modification_date: { filter: 'Modification Date', column_name: 'Modification Date' },
    asset__type__name: { filter: 'Asset Type', column_name: 'Asset Type' },
    misc__from_hotspot: { filter: 'From Hotspot', column_name: 'From Hotspot' },
    vulnerability__misc__type: { filter: 'Type', column_name: 'Type' },
    vulnerability__misc__sonarqube_tags: { filter: 'Sonarqube Tags', column_name: 'Sonarqube Tags' },
    vulnerability__misc__security_category: { filter: 'Security Category', column_name: 'Security Category' },
    vulnerability__name: { filter: 'Vulnerability Name', column_name: 'Vulnerability Name' },
    misc__filename: { filter: 'File Name', column_name: 'File Name' },
    misc__branch: { filter: 'Branch', column_name: 'Branch' },
    vulnerability__misc__effort: { filter: 'Effort', column_name: 'Effort' },
    misc__repo: { filter: 'Repository Name', column_name: 'Repository Name' },
    vulnerability__misc__owasp: { filter: 'OWASP', column_name: 'OWASP' },
    tool_output: { filter: 'Tool Output', column_name: 'Tool Output' },
    misc__cluster: { filter: 'Cluster Name', column_name: 'Cluster Name' },
    vulnerability__misc__fixid: { filter: 'Fix ID', column_name: 'Fix ID' },
    vulnerability__misc__ruleID: { filter: 'Rule ID', column_name: 'Rule ID' },
    vulnerability__misc__checkid: { filter: 'Check ID', column_name: 'Check ID' },
    vulnerability__misc__profile: { filter: 'Profile', column_name: 'Profile' },
    vulnerability__misc__version: { filter: 'Version', column_name: 'Version' },
    vulnerability__solution: { filter: 'Solution', column_name: 'Solution' },
    misc__test_number: { filter: 'Test Number', column_name: 'Test Number' },
    vulnerability__misc__compliance_type: { filter: 'Compliance Type', column_name: 'Compliance Type' },
    vulnerability__misc__group_text: { filter: 'Group Text', column_name: 'Group Text' },
    vulnerability__misc__benchmark: { filter: 'Benchmark', column_name: 'Benchmark' },
    asset__type__category: { filter: 'Asset Category', column_name: 'Asset Category' },
    vulnerability__misc__expected_result: { filter: 'Expected Result', column_name: 'Expected Result' },
    misc__namespace: { filter: 'Namespace', column_name: 'Namespace' },
    asset__host_ip: { filter: 'Asset Host IP', column_name: 'Asset Host IP' },
    asset__host_name: { filter: 'Asset Host Name', column_name: 'Asset Host Name' },
    vulnerability__misc__cve: { filter: 'CVE', column_name: 'CVE' },
    vulnerability__misc__xref: { filter: 'XREF', column_name: 'XREF' },
    vulnerability__misc__plugin_type: { filter: 'Plugin Type', column_name: 'Plugin Type' },
    vulnerability__misc__pluginFamily: { filter: 'Plugin Family', column_name: 'Plugin Family' },
    vulnerability__misc__script_version: { filter: 'Script Version', column_name: 'Script Version' },
    vulnerability__misc__check_id: { filter: 'Check ID', column_name: 'Check ID' },
    misc__framework: { filter: 'Framework', column_name: 'Framework' },
    misc__resource: { filter: 'Resource', column_name: 'Resource' },
    misc__file_path: { filter: 'File Path', column_name: 'File Path' },
    misc__email: { filter: 'Email', column_name: 'Email' },
    misc__verified: { filter: 'Verified', column_name: 'Verified' },
    misc__source_name: { filter: 'Source Name', column_name: 'Source Name' },
    misc__source_domain: { filter: 'Source Domain', column_name: 'Source Domain' },
    misc__file: { filter: 'File', column_name: 'File' },
    vulnerability__misc__detector_name: { filter: 'Detector Name', column_name: 'Detector Name' },
    vulnerability__misc__decoder_name: { filter: 'Decoder Name', column_name: 'Decoder Name' },
    misc__param: { filter: 'Params', column_name: 'Params' },
    misc__method: { filter: 'Method', column_name: 'Method' },
    misc__evidence: { filter: 'Evidence', column_name: 'Evidence' },
    vulnerability__misc__otherinfo: { filter: 'Other Info', column_name: 'Other Info' },
    vulnerability__misc__confidence: { filter: 'Confidence', column_name: 'Confidence' },
    asset__type__alias: { filter: 'Asset Type Alias', column_name: 'Asset Type Alias' },
    misc__serial_number: { filter: 'Serial Number', column_name: 'Serial Number' },
    vulnerability__misc__vulnerability_classifications: { filter: 'Vulnerability Classifications', column_name: 'Vulnerability Classifications' },
    vulnerability__misc__issueDetail: { filter: 'Issue Detail', column_name: 'Issue Detail' },
    misc__path: { filter: 'Path', column_name: 'Path' },
    misc__scan_workflow_run_url: { filter: 'Scan Workflow Run URL', column_name: 'Scan Workflow Run URL' },
    vulnerability__misc__category: { filter: 'Category', column_name: 'Category' },
    vulnerability__misc__technology: { filter: 'Technology', column_name: 'Technology' },
    vulnerability__misc__sub_category: { filter: 'Sub Category', column_name: 'Sub Category' },
    misc__scan_workflow_scan_ref: { filter: 'Branch', column_name: 'Branch' },
    misc__workflow_run_id: { filter: 'Workflow Run ID', column_name: 'Workflow Run ID' },
    misc__scan_commit: { filter: 'Scan Commit', column_name: 'Scan Commit' },
    misc__source: { filter: 'Source', column_name: 'Source' },
    misc__message: { filter: 'Finding Name', column_name: 'Finding Name' },
    misc__cloud_type: { filter: 'Cloud Account Type', column_name: 'Cloud Account Type' },
    misc__cloud_account: { filter: 'Cloud Account', column_name: 'Cloud Account' },
    vulnerability__misc__compliance: { filter: 'Compliance Name', column_name: 'Compliance Name' },
    asset__tags: { filter: 'Asset Tags', column_name: 'Asset Tags' },
    misc__threat_id: { filter: 'Threat ID', column_name: 'Threat ID' },
    vulnerability__misc__cvss_v3_score: { filter: 'CVSS v3 Score', column_name: 'CVSS v3 Score' },
    vulnerability__misc__cvss_v2_score: { filter: 'CVSS v2 Score', column_name: 'CVSS v2 Score' },
    vulnerability__misc__nvd_cvss3_vectors: { filter: 'NVD CVSS3 Vectors', column_name: 'NVD CVSS3 Vectors' },
    misc__cloud_account_type: { filter: 'Cloud Account Type', column_name: 'Cloud Account Type' },
    misc__cloud_account_id: { filter: 'Cloud Account', column_name: 'Cloud Account' },
    misc__clamAVSignature: { filter: 'Signature', column_name: 'Signature' },
    misc__os: { filter: 'OS', column_name: 'OS' },
    misc__metadata__mimetype: { filter: 'MIME Type', column_name: 'MIME Type' },
    misc__clusterName: { filter: 'Cluster Name', column_name: 'Cluster Name' },
    misc__serviceName: { filter: 'Service Name', column_name: 'Service Name' },
    misc__occurrences: { filter: 'Occurrences', column_name: 'Occurrences' },
    misc__requestMethod: { filter: 'Request Method', column_name: 'Request Method' },
    misc__requestPath: { filter: 'Request Path', column_name: 'Request Path' },
    misc__status_code: { filter: 'Status Code', column_name: 'Status Code' },
    misc__port: { filter: 'Port', column_name: 'Port' },
    misc__source_tool: { filter: 'Source Tool', column_name: 'Source Tool' },
    misc__display_location: { filter: 'Location', column_name: 'Location' },
    asset__type: { filter: 'Asset Type', column_name: 'Asset Type' },
    is_new: { filter: 'Is New', column_name: 'Is New' },
    ignored: { filter: 'Ignored', column_name: 'Ignored' },
    tickets_count: { filter: 'Tickets', column_name: 'Tickets Count' },
    vulnerability__risk_factor: { filter: 'Risk Factor', column_name: 'Risk Factor' },
    vulnerability__exploit_available: { filter: 'Exploit Available', column_name: 'Exploit Available' },
    search: { filter: 'Search', column_name: 'Search' },
  },
  categoryByDataTypeValue: {
    trivy: 'Container Image Findings',
    rra_stig: 'STIG Findings',
    kubebench: 'CIS K8s Benchmark Findings',
    nessus: 'Host-Endpoint Findings',
    'cluster-misconfiguration': 'Cluster Findings',
    'iac scan': 'IaC Findings',
    'secret scanning': 'Secret Scan Findings',
    zap: 'DAST Findings',
    burp: 'DAST Findings 2',
    cx_kics: 'CX KICS',
    cx_containers: 'CX CONTAINERS',
    sg: 'SAST Findings',
    cx_sast: 'CX SAST',
    cx_sca: 'CX SCA',
    cloudsploit: 'Cloud Findings',
    '5gscan': '5G Security Findings',
    'trivy-rootfs': 'Linux VM Vulnerability Findings',
    prowler: 'Cloud Findings',
    securityhub: 'Cloud Findings',
  },
  dataTypeNames: [
    'Container Image Findings',
    'Static Code Analysis Finding',
    'STIG Findings',
    'CIS K8s Benchmark Findings',
    'KIEM Findings',
    'Host-Endpoint Findings',
    'Cluster Findings',
    'IaC Findings',
    'Secret Scan Findings',
    'DAST Findings 1',
    'DAST Findings 2',
    'CX KICS',
    'CX CONTAINERS',
    'SAST Findings',
    'CX SAST',
    'CX SCA',
    'Cloud Findings',
    '5G Security Findings',
    'Linux VM Vulnerability Findings',
    'VM Malware Findings',
    'API Security Findings',
    'SARIF Findings',
    'Windows VM Vulnerability Findings',
    'DAST Findings',
  ],
};
